env:
  global:
    # get the latest code from master
    # - SENECA_VER=
    # to clone a specific tagged version set the version like the following:
    - SENECA_VER=#v1.3.0

  matrix:
    # plugins to test
    - TEST_SUITE=seneca-mem-store
    - TEST_SUITE=seneca-store-test
    - TEST_SUITE=seneca-postgres-store
    - TEST_SUITE=seneca-level-store
    - TEST_SUITE=seneca-mysql-store
    - TEST_SUITE=seneca-user
    - TEST_SUITE=seneca-auth
    - TEST_SUITE=seneca-web
    - TEST_SUITE=seneca
    - TEST_SUITE=seneca-basic
    - TEST_SUITE=seneca-entity
    - TEST_SUITE=seneca-transport
    - TEST_SUITE=seneca-repl
    - TEST_SUITE=seneca-cache

before_script:
  - git clone https://github.com/senecajs/$TEST_SUITE
  - if [ $TEST_SUITE = 'seneca-postgres-store' ]; then psql -U postgres -f seneca-postgres-store/docker/dbschema.sql ; fi
  - cd ./$TEST_SUITE/
  - npm i
  - npm install https://github.com/senecajs/seneca$SENECA_VER

language: node_js
sudo: false

cache:
  directories:
  - node_modules

node_js:
  - '4'

addons:
  postgresql: "9.4"

services:
  - postgresql
