env:
  - TEST_SUITE=seneca-postgres-store

language: node_js
sudo: false

node_js:
  - '5'

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - psql -U postgres -f docker/dbschema.sql
